#ifndef MEM_LOAD_H
#define MEM_LOAD_H

#include "mem_map.h"

#define EXROM_BASE ( OCM_LOW_BASE )
#define EXROM_END  ( EXROM_BASE + 0x00004000 )
#define EXROM_LENG ( EXROM_END - EXROM_BASE )

#define DAROM_BASE ( EXROM_END )
#define DAROM_END  ( DAROM_BASE + 0x00004000 )
#define DAROM_LENG ( DAROM_END - DAROM_BASE )

#define DARAM_BASE ( DAROM_END )
#define DARAM_END  ( DARAM_BASE + 0x00004000 )
#define DARAM_LENG ( DARAM_END - DARAM_BASE )

#define PGRAM0_BASE ( DARAM_END )
#define PGRAM0_END  ( OCM2_LOW_END )
#define PGRAM0_LENG ( PGRAM0_END - PGRAM0_BASE )

#define PGRAM1_BASE ( OCM3_HIGH_BASE )
#define PGRAM1_END  ( OCM3_HIGH_END )
#define PGRAM1_LENG ( PGRAM1_END - PGRAM1_BASE )

#endif // #ifndef MEM_LOAD_H
